### ISSUE TITLE
Twitch Stream Links

### ISSUE THREAD

**Issue by AlexHedley** [praeclarum/Gone#1]
Links from the stream

TODO: Add to README?

—-

jay

https://www.cs.rit.edu/~ats/projects/lp/doc/jay/package-summary.html

—-

Algorithm W - or Hindley-Milner polymorphic type inference - in F#

https://gist.github.com/praeclarum/5fbef41ea9c296590f23

—-

Structure and Interpretation of Computer Programs

https://mitpress.mit.edu/sites/default/files/sicp/index.html

The video lecture series that accompanies this book is on youtube too

https://www.youtube.com/watch?v=-J_xL4IGhJA&list=PLE18841CABEA24090

—-

Cat Language

https://github.com/cdiggins/cat-language

—-

**Comment by praeclarum** [comment]
UnrealScript reference: https://docs.unrealengine.com/udk/Two/UnrealScriptReference.html

**Comment by AlexHedley** [comment]
Was there a Partition III pdf?

**Comment by praeclarum** [comment]
ECMA-335 (CLR) Standard: https://www.ecma-international.org/publications/standards/Ecma-335.htm contains a unified PDF with all the partitions.

My Color Scheme: https://gist.github.com/praeclarum/f222d5c83ad373e8b57396663988640b

I'll get this into the README...

**Comment by praeclarum** [comment]
D Language: https://dlang.org

**Comment by praeclarum** [comment]
Thanks!

**Comment by AlexHedley** [comment]
21st Mar

ILSpy
https://github.com/icsharpcode/ILSpy

ILdasm
https://docs.microsoft.com/en-us/dotnet/framework/tools/ildasm-exe-il-disassembler

EduLink
https://codeblog.jonskeet.uk/2011/03/18/edulinq-the-e-book/

YOW! 2017 Brian Beckman - Kalman Folding for the Brave and True #YOW
https://m.youtube.com/watch?v=peJFVe-4qz4

**Comment by AlexHedley** [comment]
28th Mar

Functional GUIs with F# - .NET FRINGE Presentation
- https://praeclarum.org/2015/04/15/functional-guis.html

Real-World Functional Programming
- https://www.manning.com/books/real-world-functional-programming

Ooui
- https://github.com/praeclarum/Ooui

Fish Shell
- https://fishshell.com

**Comment by AlexHedley** [comment]
12th April 2020

Antlr
https://www.antlr.org

https://marketplace.visualstudio.com/items?itemName=mnxn.fsharp-fsl-fsy

https://fsprojects.github.io/FsLexYacc/fslex.html

https://gist.github.com/praeclarum/987fad1eb8faea91326a1a6d6c966e29

https://github.com/garethhubball/Fifth/blob/master/Fifth.Parser/Library.fs
