### ISSUE TITLE
[FR] Convert to FsLexYacc

### ISSUE THREAD

**Issue by AlexHedley** [praeclarum/Gone#9]
https://twitter.com/GarethHubball/status/1247560153609768962

https://fsprojects.github.io/FsLexYacc/

**Comment by londospark** [comment]
Remember that I've only tested on one iPhone, on one version of iOS and I'm not exactly a Xamarin[.Forms] developer so I would encourage others to test this out at their leisure. Might upload the Xamarin application that I used to test this with at some point.

**Comment by londospark** [comment]
Would anyone mind if I have a go at this please?

**Comment by praeclarum** [comment]
We did it on the show! Check out #10 

Thanks for your help @garethhubball!
